name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    - name: env
      run: env
    - name: Login to Docker Hub
      run: docker login -u shimgapi -p $DOCKER_SECRET docker.io

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-dns:latest

  push:
    runs-on: ubuntu-latest
    - name: Push image
      run: docker push docker-dns:latest
